- name: Create kernel options CRDs
  vars:
    role: '{{ item }}'
  ansible.builtin.template:
    src: 99-node-kargs.yaml
    dest: "{{ workdir }}/99-{{ item }}-kargs.yaml"
  with_items:
    - master
    - worker

- name: Apply the MachineConfig CRDs
  ansible.builtin.shell: "oc apply -f {{ workdir }}/99-{{ item }}-kargs.yaml"
  with_items:
    - master
    - worker

