---
# handlers file for ansible-squid
- name: restart squid
  ansible.builtin.service:
    name: squid
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
    enabled: yes

- name: restart chrony
  ansible.builtin.service:
    name: chronyd
    state: restarted
    daemon_reload: yes
    enabled: yes
