# tasks file for backup bastion in HA mode

- name: Copy the workdir
  ansible.posix.synchronize:
    src: "{{ workdir }}/"
    dest: "{{ workdir }}/"
    recursive: yes
  delegate_to: "{{ bastion_master }}"

- name: mkdir ~/.kube
  ansible.builtin.file:
    path: ~/.kube
    state: directory

- name: Install kubeconfig
  ansible.builtin.copy:
    src: "{{ workdir }}/auth/kubeconfig"
    dest: "~/.kube/config"

- name: Copy ignition files
  ansible.posix.synchronize:
    src: "/var/www/html/ignition/"
    dest: "/var/www/html/ignition/"
    recursive: yes
  delegate_to: "{{ bastion_master }}"

- name: Best effort SELinux repair - Apache
  ansible.builtin.shell: "restorecon -vR /var/www/html || true"
